### ISSUE TITLE
What is the continued utility of this package set?

### ISSUE THREAD

**Issue by eli-schwartz** [nicman23/arch_mate#10]
MATE 1.20 is now in the official repos, and uses gtk3. Currently these packages actually lag behind the official repos.

**Comment by nicman23** [comment]
this is the dev packages, so when 1.21 is out (the development branch), this will start to target this.

this is not for production, this is for developing (or testing) the dev branch of mate (i.e. 1.17, 1.19, 1.21)

**Comment by eli-schwartz** [comment]
Please clarify that in the pkgdesc for all packages, then.

Currently they mention nothing about "development releases", and merely claim to be the "GTK3 version" (which is redundant information because of course they are the gtk3 version, that is now the default expectation for packages).

I wasn't sure whether these packages were still meant to be from when the mate packages in [community] were having issues and lagging behind releases, and the pkgdesc seemed to suggest they were.

**Comment by nicman23** [comment]
This repo is focused on the aur and the pkgbuilds are edited automatically with a cron job. They are uploaded with the -dev suffix in the aur.
