### ISSUE TITLE
Last atril is 1.15.3 not 1.15.0...

### ISSUE THREAD

**Issue by FredBezies** [nicman23/arch_mate#3]
Looks like there is a wrong commit in atril PKGBUILD...

https://github.com/nicman23/arch_mate/commit/fbc8b751fca447c332548a92c1f48212fb0cccfc

**Comment by FredBezies** [comment]
Oops, spoke too fast. Sorry !

**Comment by nicman23** [comment]
sry did not comment out git push in some tests that i run :P

**Comment by FredBezies** [comment]
:)

**Comment by nicman23** [comment]
wait. did you write and delete a comment? that or github is fucked

**Comment by FredBezies** [comment]
I wrote a small and kinda useless comment. Don't worry.
