### ISSUE TITLE
Use the same pkgname used in AUR

### ISSUE THREAD

**Issue by rafaelsoaresbr** [nicman23/arch_mate#4]
Why not put the same pkgnames used in AUR ("${_pkgbase}-${_ver}-gtk3")?
Or something like "${_pkgbase}-unstable-gtk3"?

**Comment by nicman23** [comment]
If I understand correctly... because they are generated from aur-env.sh and it is a simple variable change to update from 1.15 to 1.16

**Comment by nicman23** [comment]
No wait I'm stupid. 

The reason is that gtk3 was announced stable and the gtk2 branch will probably be deprecated

**Comment by rafaelsoaresbr** [comment]
Sorry, I misunderstood the reason to include these packages in AUR. I thought it was to allow the installation of the MATE Desktop's development branches (1.15, 1.17, 1.19 ...)

**Comment by nicman23** [comment]
Seeing as you are probably a TU, how can I delete multiple packages? :(

**Comment by rafaelsoaresbr** [comment]
I'm not a TU. :(
Great work you've done here.
