### ISSUE TITLE
Rebrand needed.

### ISSUE THREAD

**Issue by nicman23** [nicman23/arch_mate#5]
As I was made aware that there is a new maintainer on community (1.14 for now), I/ we need to change the names on the aur for the current to something like _pkgbase-dev.

**Comment by rafaelsoaresbr** [comment]
I suggest changing the name of the folder caja-extensions-common to caja-extensions and include a new folder caja-extensions-gtk3 to follow [Community]'s naming, also include the new package caja-wallpapper to both _pkgbase.
I can help you with this.
https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/caja-extensions

**Comment by nicman23** [comment]
Sure :) , although, community did not change the pkgname just pkgbase which is internal only to the PKGBUILD.

**Comment by nicman23** [comment]
First commit in aur done. Now under _pkgbase-dev :)
